tags:
  - Tasks
summary: Get tasks by month
operationId: getTasksByMonth
description: 'Get Task by Month'
security:
  - bearerAuth: []
parameters:
  - in: query
    name: year
    schema:
      type: integer
    example: 2025
  - in: query
    name: month
    schema:
      type: integer
    example: 08
responses:
  '200':
    description: 'Get Task by month'
    content:
      application/json:
        schema:
          type: object
          required:
           - status
           - message
           - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully found Tasks from 2025-08-29!
            data:
              type: object
              $ref: ..\..\..\components\schemas\tasks.yaml
  '404':
    $ref: ..\..\..\components\responses\404.yaml

