tags:
  - Tasks
summary: Change task by ID
operationId: ChangeTask
description: 'Change a task by ID'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
      example: 6692528c222b4be7b4b17ebd
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          task:
            definitions: "task name"
            type: string
            example: dddhh aayyz

          timeDeclaration:
            definitions: "task's time, min"
            type: number
            example: 120

          date:
            definitions: "task's date & time"
            type: date
            example: "2025-09-10T18:10:00.000+00:10"

          isFavourite:
            definitions: "Would you like or not?"
            type: boolean
            example: false

          taskType:
            definitions: "task's work place"
            type: string
            example: work
            enum: ['work', 'home', 'personal']
            default: 'personal'
          status:
            definitions: "task's status"
            type: string
            example: pending
            enum: ['completed', 'pending','working']
            default: 'personal'
          timeReal:
            definitions: "task's time, min"
            type: number
            example: 120
responses:
  '200':
    description: Change a task
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully changed a task!
            data:
              type: object
              $ref: ..\..\..\components\schemas\tasks.yaml
  '404':
    $ref: ..\..\..\components\responses\404.yaml

