openapi: 3.1.0
info:
  version: 1.0.0
  title: Taskts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
   This is Task app
tags:
  - name: Tasks
    description: Operation with Tasks
  - name: Auth
    description: Auth operations
servers:
  - url: http://localhost:3000
  - url: https://timemanagement-back.onrender.com
paths:

  /tasks:
    get:
      $ref: ..\swagger\paths\tasks\get.yaml
    post:
      $ref: ..\swagger\paths\tasks\post.yaml
  /tasks/{id}:
    get:
      $ref: ..\swagger\paths\tasks\{id}\get.yaml
    delete:
      $ref: ..\swagger\paths\tasks\{id}\delete.yaml
    patch:
      $ref: ..\swagger\paths\tasks\{id}\patch.yaml

  /note:
    get:
      $ref: ..\swagger\paths\notes\get.yaml
    post:
      $ref: ..\swagger\paths\notes\post.yaml
  /note/{id}:
    get:
      $ref: ..\swagger\paths\notes\{id}\get.yaml
    delete:
      $ref: ..\swagger\paths\notes\{id}\delete.yaml
    patch:
      $ref: ..\swagger\paths\notes\{id}\patch.yaml

  /resurse:
    get:
      $ref: ..\swagger\paths\resurses\get.yaml
    post:
      $ref: ..\swagger\paths\resurses\post.yaml
  /resurse/{id}:
    get:
      $ref: ..\swagger\paths\resurses\{id}\get.yaml
    delete:
      $ref: ..\swagger\paths\resurses\{id}\delete.yaml
    patch:
      $ref: ..\swagger\paths\resurses\{id}\patch.yaml

  /auth/confirm-auth:
    post:
      $ref: ..\swagger\paths\auth\confirm-oauth\post.yaml
  /auth/logaut:
    post:
      $ref: ..\swagger\paths\auth\logout\post.yaml
  /auth/login:
    post:
      $ref: ..\swagger\paths\auth\login\post.yaml
  /auth/refresh:
    post:
      $ref: ..\swagger\paths\auth\refresh\post.yaml
  /auth/register:
    post:
      $ref: ..\swagger\paths\auth\register\post.yaml
  /auth/reset-pwd:
    post:
      $ref: ..\swagger\paths\auth\reset-pwd\post.yaml
  /auth/send-reset-email:
    post:
      $ref: ..\swagger\paths\auth\send-reset-email\post.yaml
  /auth/get-oauth-url:
    get:
      $ref: ..\swagger\paths\auth\get-oauth-url\get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
